version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/ReportReviewer/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
    - dependency-name: "@types/node"
      update-types: ["version-update:semver-major"]
  
  - package-ecosystem: "npm"
    directory: "/src/DotNetFormatCLI/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(DotNetFormatCLI)"
      include: "scope"
    ignore:
    - dependency-name: "@types/node"
      update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/src/UseDotNetFormat/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(UseDotNetFormat)"
      include: "scope"
    ignore:
    - dependency-name: "@types/node"
      update-types: ["version-update:semver-major"]