version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: monthly
      timezone: "Asia/Ho_Chi_Minh"
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: "npm"
    directories: [
        "/src/ReportReviewer/V1",
        "/src/DotNetFormatCLI/V1",
        "/src/UseDotNetFormat/V1"
      ]
    schedule:
      interval: monthly
      timezone: "Asia/Ho_Chi_Minh"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      monorepo-dependencies:
        group-by: dependency-name
    ignore:
    - dependency-name: "*"
      update-types: [ "version-update:semver-major" ]
