trigger:
  branches:
    include:
      - main
      - 'feature/*'
  paths:
    include:
    - 'src/*'

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '10.x'
- task: TfxInstaller@3
  inputs: 
    version: 'v0.8.x'
    checkLatest: true
- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  inputs:
    command: 'tsc'
- task: QueryAzureDevOpsExtensionVersion@3
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'ServiceConnection' # Change to whatever you named the service connection
    publisherId: '$(PublisherID)'
    extensionId: '$(ExtensionID)'
    versionAction: 'Patch'
    outputVariable: 'Task.Extension.Version'
- task: PackageAzureDevOpsExtension@3
  inputs:
    rootFolder: '$(System.DefaultWorkingDirectory)'
    publisherId: '$(PublisherID)'
    extensionId: '$(ExtensionID)'
    extensionName: '$(ExtensionName)'
    extensionVersion: '$(Task.Extension.Version)'
    updateTasksVersion: false
    updateTasksVersionType: 'patch'
    extensionVisibility: 'private' # Change to public if you're publishing to the marketplace
    extensionPricing: 'free'
- task: CopyFiles@2
  displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
  inputs:
    Contents: "**/*.vsix"
    TargetFolder: "$(Build.ArtifactStagingDirectory)"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(ArtifactName)'
    publishLocation: 'Container'