trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'V0'
    jobs:
      - job: "NET_3"
        steps:
          - checkout: self
            lfs: false

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk 3.x'
            inputs:
              useGlobalJson: true
              workingDirectory: tests/dotnet3.1/

          - task: DotNetFormatCLI@0
            displayName: '[net3.1] check'
            inputs:
              onlyChangedFiles: true
            continueOnError: true
            condition: succeededOrFailed()

      - job: "NET_5"
        steps:
          - checkout: self
            lfs: false

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk 5.x'
            inputs:
              useGlobalJson: true
              workingDirectory: tests/dotnet5/

          - task: DotNetFormatCLI@0
            displayName: '[net5] check'
            inputs:
              onlyChangedFiles: true
            continueOnError: true
            condition: succeededOrFailed()

      - job: "NET_6"
        steps:
          - checkout: self
            lfs: false

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk 6.x'
            inputs:
              useGlobalJson: true
              workingDirectory: tests/dotnet6/

          - task: DotNetFormatCLI@0
            displayName: '[net6] check'
            inputs:
              onlyChangedFiles: true
            continueOnError: true
            condition: succeededOrFailed()

      - job: "NET_7"
        steps:
          - checkout: self
            lfs: false

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk 7.x'
            inputs:
              useGlobalJson: true
              workingDirectory: tests/dotnet7/

          - task: DotNetFormatCLI@0
            displayName: '[net7] check'
            inputs:
              onlyChangedFiles: true
            continueOnError: true
            condition: succeededOrFailed()

      - job: "NET_8"
        steps:
          - checkout: self
            lfs: false

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk 8.x'
            inputs:
              useGlobalJson: true
              workingDirectory: tests/dotnet8/

          - task: DotNetFormatCLI@0
            displayName: '[net8] check'
            inputs:
              onlyChangedFiles: true
            continueOnError: true
            condition: succeededOrFailed()

  - stage: 'V1'
    jobs:
      - job: "NET_3"
        steps:
          - checkout: self
            lfs: false

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk 3.x'
            inputs:
              useGlobalJson: true
              workingDirectory: tests/dotnet3.1/

          - task: DotNetFormatCLI@1
            displayName: '[net3.1] check'
            inputs:
              onlyChangedFiles: true
            continueOnError: true
            condition: succeededOrFailed()

      - job: "NET_5"
        steps:
          - checkout: self
            lfs: false

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk 5.x'
            inputs:
              useGlobalJson: true
              workingDirectory: tests/dotnet5/

          - task: DotNetFormatCLI@1
            displayName: '[net5] check'
            inputs:
              onlyChangedFiles: true
            continueOnError: true
            condition: succeededOrFailed()

      - job: "NET_6"
        steps:
          - checkout: self
            lfs: false

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk 6.x'
            inputs:
              useGlobalJson: true
              workingDirectory: tests/dotnet6/

          - task: DotNetFormatCLI@1
            displayName: '[net6] check'
            inputs:
              onlyChangedFiles: true
            continueOnError: true
            condition: succeededOrFailed()

      - job: "NET_7"
        steps:
          - checkout: self
            lfs: false

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk 7.x'
            inputs:
              useGlobalJson: true
              workingDirectory: tests/dotnet7/

          - task: DotNetFormatCLI@1
            displayName: '[net7] check'
            inputs:
              onlyChangedFiles: true
            continueOnError: true
            condition: succeededOrFailed()

      - job: "NET_8"
        steps:
          - checkout: self
            lfs: false

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk 8.x'
            inputs:
              useGlobalJson: true
              workingDirectory: tests/dotnet8/

          - task: DotNetFormatCLI@1
            displayName: '[net8] check'
            inputs:
              onlyChangedFiles: true
            continueOnError: true
            condition: succeededOrFailed()
